// <auto-generated />
using System;
using HeroApp.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Heroes.Data.Migrations
{
    [DbContext(typeof(HeroesDbContext))]
    [Migration("20181218145631_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeroApp.Data.Domain.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Advantage");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Advantage = 50.0,
                            Name = "Super Strength"
                        },
                        new
                        {
                            Id = 2,
                            Advantage = 50.0,
                            Name = "Super Speed"
                        },
                        new
                        {
                            Id = 3,
                            Advantage = 50.0,
                            Name = "Super Stamina"
                        },
                        new
                        {
                            Id = 4,
                            Advantage = 50.0,
                            Name = "Super Agility"
                        },
                        new
                        {
                            Id = 5,
                            Advantage = 75.0,
                            Name = "Genius Intellect"
                        },
                        new
                        {
                            Id = 6,
                            Advantage = 15.0,
                            Name = "Flight"
                        },
                        new
                        {
                            Id = 7,
                            Advantage = 15.0,
                            Name = "Regenerative life support"
                        },
                        new
                        {
                            Id = 8,
                            Advantage = 15.0,
                            Name = "Super healing"
                        },
                        new
                        {
                            Id = 9,
                            Advantage = 15.0,
                            Name = "Energy repolsors"
                        },
                        new
                        {
                            Id = 10,
                            Advantage = 100.0,
                            Name = "Invulnerability"
                        },
                        new
                        {
                            Id = 11,
                            Advantage = 180.0,
                            Name = "Electric Manipulation"
                        },
                        new
                        {
                            Id = 12,
                            Advantage = 10.0,
                            Name = "Weather Manipulation"
                        },
                        new
                        {
                            Id = 13,
                            Advantage = 10.0,
                            Name = "Vibranium claws"
                        },
                        new
                        {
                            Id = 14,
                            Advantage = 10.0,
                            Name = "Mastery of Magic"
                        },
                        new
                        {
                            Id = 15,
                            Advantage = 10.0,
                            Name = "Manipulation of Space and Time"
                        },
                        new
                        {
                            Id = 16,
                            Advantage = 10.0,
                            Name = "Spider sense"
                        },
                        new
                        {
                            Id = 17,
                            Advantage = 10.0,
                            Name = "Ability to cling to any surface"
                        },
                        new
                        {
                            Id = 18,
                            Advantage = 99.0,
                            Name = "Genius"
                        },
                        new
                        {
                            Id = 19,
                            Advantage = 10.0,
                            Name = "Billionaire"
                        },
                        new
                        {
                            Id = 20,
                            Advantage = 10.0,
                            Name = "Playboy"
                        },
                        new
                        {
                            Id = 21,
                            Advantage = 10.0,
                            Name = "Philanthropist"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Genius. Billionaire. Playboy. Philanthropist. Tony Stark's confidence is only matched by his high-flying abilities as the hero called Iron Man.",
                            Name = "Iron Man"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The son of Odin uses his mighty abilities as the God of Thunder to protect his home Asgard and planet Earth alike.",
                            Name = "Thor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Leader of the Guardians of the Galaxy, Peter Quill, known as Star-Lord, brings a sassy sense of humor while protecting the universe from any and all threats.",
                            Name = "Star-Lord"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Recipient of the Super-Soldier serum, World War II hero Steve Rogers fights for American ideals as one of the world’s mightiest heroes and the leader of the Avengers.",
                            Name = "Captain America"
                        },
                        new
                        {
                            Id = 5,
                            Description = "T’Challa is the king of the secretive and highly advanced African nation of Wakanda - as well as the powerful warrior known as the Black Panther.",
                            Name = "Black Panter"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Formerly a renowned surgeon, Doctor Stephen Strange now serves as the Sorcerer Supreme—Earth’s foremost protector against magical and mystical threats.",
                            Name = "Dr Strange"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dr. Bruce Banner lives a life caught between the soft-spoken scientist he’s always been and the uncontrollable green monster powered by his rage.",
                            Name = "Hulk"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles.",
                            Name = "Spider-Man"
                        },
                        new
                        {
                            Id = 9,
                            Description = "When ex-criminal Scott Lang turned to his illicit skills in order to save his daughter’s life, he unexpectedly became the size-shifting, insect-commanding Super Hero known as Ant-Man!",
                            Name = "Ant-Man"
                        },
                        new
                        {
                            Id = 10,
                            Description = "James Buchanan “Bucky” Barnes enlists to fight in World War II, but eventually literally falls in battle. Unfortunately, the evil Arnim Zola recovers him and erases his memory, turning him into a highly-trained assassin called the Winter Soldier.",
                            Name = "Winter Soldier"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.HeroAbility", b =>
                {
                    b.Property<int>("HeroId");

                    b.Property<int>("AbilityId");

                    b.HasKey("HeroId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("HeroAbilities");

                    b.HasData(
                        new
                        {
                            HeroId = 1,
                            AbilityId = 18
                        },
                        new
                        {
                            HeroId = 1,
                            AbilityId = 19
                        },
                        new
                        {
                            HeroId = 1,
                            AbilityId = 20
                        },
                        new
                        {
                            HeroId = 1,
                            AbilityId = 21
                        },
                        new
                        {
                            HeroId = 2,
                            AbilityId = 1
                        },
                        new
                        {
                            HeroId = 2,
                            AbilityId = 3
                        },
                        new
                        {
                            HeroId = 2,
                            AbilityId = 10
                        },
                        new
                        {
                            HeroId = 3,
                            AbilityId = 5
                        },
                        new
                        {
                            HeroId = 4,
                            AbilityId = 1
                        },
                        new
                        {
                            HeroId = 4,
                            AbilityId = 2
                        },
                        new
                        {
                            HeroId = 4,
                            AbilityId = 3
                        },
                        new
                        {
                            HeroId = 4,
                            AbilityId = 4
                        },
                        new
                        {
                            HeroId = 4,
                            AbilityId = 10
                        },
                        new
                        {
                            HeroId = 5,
                            AbilityId = 1
                        },
                        new
                        {
                            HeroId = 5,
                            AbilityId = 2
                        },
                        new
                        {
                            HeroId = 5,
                            AbilityId = 3
                        },
                        new
                        {
                            HeroId = 5,
                            AbilityId = 4
                        },
                        new
                        {
                            HeroId = 5,
                            AbilityId = 10
                        },
                        new
                        {
                            HeroId = 6,
                            AbilityId = 5
                        },
                        new
                        {
                            HeroId = 6,
                            AbilityId = 14
                        },
                        new
                        {
                            HeroId = 7,
                            AbilityId = 1
                        },
                        new
                        {
                            HeroId = 7,
                            AbilityId = 3
                        },
                        new
                        {
                            HeroId = 7,
                            AbilityId = 8
                        },
                        new
                        {
                            HeroId = 7,
                            AbilityId = 10
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 1
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 2
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 3
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 4
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 16
                        },
                        new
                        {
                            HeroId = 8,
                            AbilityId = 17
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<string>("PlotSummary");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/710bfuwiwiL._SY450_.jpg",
                            PlotSummary = "2008's Iron Man tells the story of Tony Stark, a billionaire industrialist and genius inventor who is kidnapped and forced to build a devastating weapon. Instead, using his intelligence and ingenuity, Tony builds a high-tech suit of armor and escapes captivity. When he uncovers a nefarious plot with global implications, he dons his powerful armor and vows to protect the world as Iron Man.",
                            ReleaseDate = new DateTime(2008, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Man"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_.jpg",
                            PlotSummary = "In this new beginning, scientist Bruce Banner desperately hunts for a cure to the gamma radiation that poisoned his cells and unleashes the unbridled force of rage within him: The Hulk. Living in the shadows--cut off from a life he knew and the woman he loves, Betty Ross--Banner struggles to avoid the obsessive pursuit of his nemesis, General Thunderbolt Ross and the military machinery that seeks to capture him and brutally exploit his power. As all three grapple with the secrets that led to the Hulk's creation, they are confronted with a monstrous new adversary known as the Abomination, whose destructive strength exceeds even the Hulk's own. One scientist must make an agonizing final choice: accept a peaceful life as Bruce Banner or find heroism in the creature he holds inside--The Incredible Hulk.",
                            ReleaseDate = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Incredible Hulk"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/81sC6pkIARL._SY445_.jpg",
                            PlotSummary = "With the world now aware that he is Iron Man, billionaire inventor Tony Stark faces pressure from all sides to share his technology with the military. He is reluctant to divulge the secrets of his armored suit, fearing the information will fall into the wrong hands. With Pepper Potts and 'Rhodey' Rhodes by his side, Tony must forge new alliances and confront a powerful new enemy.",
                            ReleaseDate = new DateTime(2010, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Man 2"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://i.pinimg.com/originals/fd/f0/af/fdf0af82063887c10cad7a3ecc6822cb.jpg",
                            PlotSummary = "As the son of Odin, king of the Norse gods, Thor will soon inherit the throne of Asgard from his aging father. However, on the day that he is to be crowned, Thor reacts with brutality when the gods' enemies, the Frost Giants, enter the palace in violation of their treaty. As punishment, Odin banishes Thor to Earth. While Loki, Thor's brother, plots mischief in Asgard, Thor, now stripped of his powers, faces his greatest threat.",
                            ReleaseDate = new DateTime(2011, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thor"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/51Xp%2B8qDCbL.jpg",
                            PlotSummary = "Marvel's 'Captain America: The First Avenger' focuses on the early days of the Marvel Universe when Steve Rogers volunteers to participate in an experimental program that turns him into the Super Soldier known as Captain America.",
                            ReleaseDate = new DateTime(2011, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Captain America: The First Avenger"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/719SFBdxRtL._SY679_.jpg",
                            PlotSummary = "Marvel Studios presents in association with Paramount Pictures 'Marvel's The Avengers'--the super hero team up of a lifetime, featuring iconic Marvel super heroes Iron Man, the Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When an unexpected enemy emerges that threatens global safety and security, Nick Fury, Director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins.",
                            ReleaseDate = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/71aYephNm9L._SY606_.jpg",
                            PlotSummary = "Marvel's 'Iron Man 3' pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy's hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man.",
                            ReleaseDate = new DateTime(2013, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Man 3"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/71O3WJv6XzL._SY606_.jpg",
                            PlotSummary = "In the aftermath of Marvel's 'Thor' and 'Marvel's The Avengers,' Thor fights to restore order across the cosmos...but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.",
                            ReleaseDate = new DateTime(2013, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thor: The Dark World"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/avengersageofultron_lob_crd_03_0.jpg",
                            PlotSummary = "Marvel Studios presents “Avengers: Age of Ultron,” the epic follow-up to the biggest Super Hero movie of all time. When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes, including Iron Man, Captain America, Thor, The Incredible Hulk, Black Widow and Hawkeye, are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to the Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Age of Ultron"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/captainamericacivilwar_lob_crd_01_10.jpg",
                            PlotSummary = "Marvel’s “Captain America: Civil War” finds Steve Rogers leading the newly formed team of Avengers in their continued efforts to safeguard humanity. But after another incident involving the Avengers results in collateral damage, political pressure mounts to install a system of accountability, headed by a governing body to oversee and direct the team. The new status quo fractures the Avengers, resulting in two camps—one led by Steve Rogers and his desire for the Avengers to remain free to defend humanity without government interference, and the other following Tony Stark’s surprising decision to support government oversight and accountability.",
                            ReleaseDate = new DateTime(2016, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Captain America: Civil War"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/doctorstrange_lob_crd_01_7.jpg",
                            PlotSummary = "From Marvel Studios comes “Doctor Strange,” the story of world-famous neurosurgeon Dr. Stephen Strange whose life changes forever after a horrific car accident robs him of the use of his hands. When traditional medicine fails him, he is forced to look for healing, and hope, in an unlikely place—a mysterious enclave known as Kamar-Taj. He quickly learns that this is not just a center for healing but also the front line of a battle against unseen dark forces bent on destroying our reality. Before long Strange—armed with newly acquired magical powers—is forced to choose whether to return to his life of fortune and status or leave it all behind to defend the world as the most powerful sorcerer in existence.",
                            ReleaseDate = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Doctor Strange"
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/blackpanther_lob_crd_01_5.jpg",
                            PlotSummary = "Marvel Studios’ “Black Panther” follows T’Challa who, after the death of his father, the King of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king. But when a powerful old enemy reappears, T’Challa’s mettle as king—and Black Panther—is tested when he is drawn into a formidable conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people and their way of life.",
                            ReleaseDate = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://terrigen-cdn-dev.marvel.com/content/prod/1x/avengersinfinitywar_lob_crd_02.jpg",
                            PlotSummary = "An unprecedented cinematic journey ten years in the making and spanning the entire Marvel Cinematic Universe, Marvel Studios' 'Avengers: Infinity War' brings to the screen the ultimate, deadliest showdown of all time. As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                            ReleaseDate = new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Infinity War"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.SecretIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<int>("HeroId");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("SecretIdentities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tony",
                            HeroId = 1,
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Peter",
                            HeroId = 3,
                            LastName = "Quill"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Steve",
                            HeroId = 4,
                            LastName = "Rogers"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "T'Challa",
                            HeroId = 5
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Steven",
                            HeroId = 6,
                            LastName = "Strange"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Bruce",
                            HeroId = 7,
                            LastName = "Banner"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Peter",
                            HeroId = 8,
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Scott",
                            HeroId = 9,
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Bucky",
                            HeroId = 10,
                            LastName = "Barnes"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("LeaderId");

                    b.Property<int>("MovieId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.HasIndex("MovieId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeaderId = 1,
                            MovieId = 1,
                            Name = "Iron Man"
                        },
                        new
                        {
                            Id = 2,
                            LeaderId = 7,
                            MovieId = 2,
                            Name = "The Incredible Hulk"
                        },
                        new
                        {
                            Id = 3,
                            LeaderId = 1,
                            MovieId = 3,
                            Name = "Iron Man 2"
                        },
                        new
                        {
                            Id = 4,
                            LeaderId = 2,
                            MovieId = 4,
                            Name = "Thor"
                        },
                        new
                        {
                            Id = 5,
                            LeaderId = 4,
                            MovieId = 5,
                            Name = "Captain America: The First Avenger"
                        },
                        new
                        {
                            Id = 6,
                            LeaderId = 1,
                            MovieId = 6,
                            Name = "Avengers"
                        },
                        new
                        {
                            Id = 7,
                            LeaderId = 1,
                            MovieId = 7,
                            Name = "Iron Man 3"
                        },
                        new
                        {
                            Id = 8,
                            LeaderId = 1,
                            MovieId = 8,
                            Name = "Thor: The Dark World"
                        },
                        new
                        {
                            Id = 9,
                            LeaderId = 1,
                            MovieId = 10,
                            Name = "Team Tony"
                        },
                        new
                        {
                            Id = 10,
                            LeaderId = 4,
                            MovieId = 10,
                            Name = "Team Cap"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.TeamMember", b =>
                {
                    b.Property<int>("TeamId");

                    b.Property<int>("MemberId");

                    b.HasKey("TeamId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 2,
                            MemberId = 7
                        },
                        new
                        {
                            TeamId = 3,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 4,
                            MemberId = 2
                        },
                        new
                        {
                            TeamId = 5,
                            MemberId = 4
                        },
                        new
                        {
                            TeamId = 6,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 6,
                            MemberId = 2
                        },
                        new
                        {
                            TeamId = 6,
                            MemberId = 4
                        },
                        new
                        {
                            TeamId = 6,
                            MemberId = 7
                        },
                        new
                        {
                            TeamId = 7,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 7,
                            MemberId = 7
                        },
                        new
                        {
                            TeamId = 8,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 8,
                            MemberId = 4
                        },
                        new
                        {
                            TeamId = 9,
                            MemberId = 1
                        },
                        new
                        {
                            TeamId = 9,
                            MemberId = 5
                        },
                        new
                        {
                            TeamId = 9,
                            MemberId = 8
                        },
                        new
                        {
                            TeamId = 10,
                            MemberId = 4
                        },
                        new
                        {
                            TeamId = 10,
                            MemberId = 9
                        },
                        new
                        {
                            TeamId = 10,
                            MemberId = 10
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Advantage");

                    b.Property<string>("Description");

                    b.Property<int?>("HeroId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Advantage = 250.0,
                            HeroId = 1,
                            Name = "Iron Man Armor"
                        },
                        new
                        {
                            Id = 2,
                            Advantage = 300.0,
                            HeroId = 2,
                            Name = "Mjolnir"
                        },
                        new
                        {
                            Id = 3,
                            Advantage = 150.0,
                            HeroId = 3,
                            Name = "Jet Boots"
                        },
                        new
                        {
                            Id = 4,
                            Advantage = 150.0,
                            HeroId = 4,
                            Name = "Vibranium shield"
                        },
                        new
                        {
                            Id = 5,
                            Advantage = 300.0,
                            HeroId = 5,
                            Name = "Vibranium armor"
                        },
                        new
                        {
                            Id = 6,
                            Advantage = 120.0,
                            HeroId = 6,
                            Name = "Cloak of levitation"
                        },
                        new
                        {
                            Id = 7,
                            Advantage = 600.0,
                            HeroId = 6,
                            Name = "Eye of Agamotto"
                        },
                        new
                        {
                            Id = 8,
                            Advantage = 10.0,
                            HeroId = 8,
                            Name = "Spidey suit"
                        },
                        new
                        {
                            Id = 9,
                            Advantage = 150.0,
                            HeroId = 8,
                            Name = "Web shooters"
                        },
                        new
                        {
                            Id = 10,
                            Advantage = 250.0,
                            HeroId = 9,
                            Name = "Ant-Man Suit"
                        },
                        new
                        {
                            Id = 11,
                            Advantage = 999.0,
                            Name = "Infinity Gauntlet"
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.WeaponAbility", b =>
                {
                    b.Property<int>("WeaponId");

                    b.Property<int>("AbilityId");

                    b.HasKey("WeaponId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("WeaponAbilities");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            AbilityId = 1
                        },
                        new
                        {
                            WeaponId = 1,
                            AbilityId = 6
                        },
                        new
                        {
                            WeaponId = 1,
                            AbilityId = 7
                        },
                        new
                        {
                            WeaponId = 1,
                            AbilityId = 9
                        },
                        new
                        {
                            WeaponId = 1,
                            AbilityId = 2
                        },
                        new
                        {
                            WeaponId = 2,
                            AbilityId = 6
                        },
                        new
                        {
                            WeaponId = 2,
                            AbilityId = 11
                        },
                        new
                        {
                            WeaponId = 2,
                            AbilityId = 12
                        },
                        new
                        {
                            WeaponId = 3,
                            AbilityId = 6
                        },
                        new
                        {
                            WeaponId = 5,
                            AbilityId = 13
                        },
                        new
                        {
                            WeaponId = 6,
                            AbilityId = 6
                        },
                        new
                        {
                            WeaponId = 7,
                            AbilityId = 15
                        });
                });

            modelBuilder.Entity("HeroApp.Data.Domain.HeroAbility", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Ability", "Ability")
                        .WithMany("LinkedHeroes")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeroApp.Data.Domain.Hero", "Hero")
                        .WithMany("LinkedAbilities")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HeroApp.Data.Domain.SecretIdentity", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Hero", "Hero")
                        .WithOne("SecretIdentity")
                        .HasForeignKey("HeroApp.Data.Domain.SecretIdentity", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Team", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Hero", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeroApp.Data.Domain.Movie", "Movie")
                        .WithMany("Teams")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HeroApp.Data.Domain.TeamMember", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Hero", "Member")
                        .WithMany("LinkedTeams")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeroApp.Data.Domain.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HeroApp.Data.Domain.Weapon", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Hero", "Hero")
                        .WithMany("Weapons")
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("HeroApp.Data.Domain.WeaponAbility", b =>
                {
                    b.HasOne("HeroApp.Data.Domain.Ability", "Ability")
                        .WithMany("LinkedWeapons")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeroApp.Data.Domain.Weapon", "Weapon")
                        .WithMany("LinkedAbilities")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
